baseline2

diff --git a/tests/ci/yardstick-verify b/tests/ci/yardstick-verify
--- a/tests/ci/yardstick-verify
+++ b/tests/ci/yardstick-verify
@@ -87,9 +87,7 @@ error_exit()
         exitcode=$rc
     fi
 
-    if [[ "${DEPLOY_SCENARIO:0:2}" == 'os' ]];then
-        source "${YARDSTICK_REPO_DIR}/tests/ci/clean_images.sh"
-    fi
+    cleanup
 
     echo "Exiting with RC=$exitcode"
 
@@ -101,8 +99,8 @@ set -o pipefail
 
 install_storperf()
 {
-    # Install Storper on huawei-pod1 and huawei-pod2
-    if [ "$NODE_NAME" == "huawei-pod1" -o "$NODE_NAME" == "huawei-pod2" ]; then
+    # Install Storper on huawei-pod1
+    if [ "$NODE_NAME" == "huawei-pod1" ]; then
         echo
         echo "========== Installing storperf =========="
 
@@ -116,8 +114,8 @@ install_storperf()
 
 remove_storperf()
 {
-    # remove Storper from huawei-pod1 and huawei-pod2
-    if [ "$NODE_NAME" == "huawei-pod1" -o "$NODE_NAME" == "huawei-pod2" ]; then
+    # remove Storper from huawei-pod1
+    if [ "$NODE_NAME" == "huawei-pod1" ]; then
         echo
         echo "========== Removing storperf =========="
 
@@ -250,38 +248,6 @@ EOF
 
 }
 
-check_openstack(){
-    # check if some necessary variables is set
-    if [ -z "$OS_AUTH_URL" ]; then
-        echo "OS_AUTH_URL is unset or empty"
-        exit 1
-    fi
-
-    echo "OS_AUTH_URL is $OS_AUTH_URL"
-    echo
-
-    # check OpenStack services
-    if [[ $OS_INSECURE ]] && [[ "$(echo $OS_INSECURE | tr '[:upper:]' '[:lower:]')" = "true" ]]; then
-        SECURE="--insecure"
-    else
-        SECURE=""
-    fi
-    echo "Checking OpenStack services:"
-    for cmd in "openstack ${SECURE} image list" "openstack ${SECURE} server list" "openstack ${SECURE} stack list"; do
-        echo "  checking ${cmd} ..."
-        if ! $cmd >/dev/null; then
-            echo "error: command \"$cmd\" failed"
-            exit 1
-        fi
-    done
-
-    echo
-    echo "Checking for External network:"
-    for net in $(openstack network list --external -c Name -f value); do
-        echo "  external network: $net"
-    done
-}
-
 main()
 {
     GITROOT=$(cd $(dirname $0) && git rev-parse --show-toplevel)
@@ -317,15 +283,36 @@ main()
     done
     echo
 
-    trap "error_exit" EXIT SIGTERM
-
-    if [[ "${DEPLOY_SCENARIO:0:2}" == "os" ]];then
-        check_openstack
-
-        source $YARDSTICK_REPO_DIR/tests/ci/clean_images.sh
-        source $YARDSTICK_REPO_DIR/tests/ci/load_images.sh
+    # check if some necessary variables is set
+    if [ -z "$OS_AUTH_URL" ]; then
+        echo "OS_AUTH_URL is unset or empty"
+        exit 1
     fi
 
+    echo "OS_AUTH_URL is $OS_AUTH_URL"
+    echo
+
+    # check OpenStack services
+    echo "Checking OpenStack services:"
+    for cmd in "openstack image list" "openstack server list" "openstack stack list"; do
+        echo "  checking ${cmd} ..."
+        if ! $cmd >/dev/null; then
+            echo "error: command \"$cmd\" failed"
+            exit 1
+        fi
+    done
+
+    echo
+    echo "Checking for External network:"
+    for net in $(openstack network list --external -c Name -f value); do
+        echo "  external network: $net"
+    done
+
+    source $YARDSTICK_REPO_DIR/tests/ci/clean_images.sh
+
+    trap "error_exit" EXIT SIGTERM
+
+    source $YARDSTICK_REPO_DIR/tests/ci/load_images.sh
     install_storperf
     run_test
     remove_storperf
diff --git a/tools/yardstick-img-dpdk-modify b/tools/yardstick-img-dpdk-modify
--- a/tools/yardstick-img-dpdk-modify
+++ b/tools/yardstick-img-dpdk-modify
@@ -23,7 +23,6 @@
 #
 # TODO: image resize is needed if the base image is too small
 #
-
 set -e
 set -x
 
@@ -36,20 +35,29 @@ test $# -eq 1 || die "no image specific script as argument"
 test $(id -u) -eq 0 || die "should invoke using sudo"
 
 cmd=$1
+RELEASE=$2
 test -x $cmd
 mountdir="/mnt/yardstick"
 
 workspace=${WORKSPACE:-"/tmp/workspace/yardstick"}
 host=${HOST:-"cloud-images.ubuntu.com"}
-release=${RELEASE:-"wily"}
-image_path="${release}/current/${release}-server-cloudimg-amd64-disk1.img"
+release=${RELEASE:-"xenial"}
+boot_mode="disk1"
+if [[ "${YARD_IMG_ARCH}" = "arm64" ]]; then
+    boot_mode="uefi1"
+fi
+
+image_path="${release}/current/${release}-server-cloudimg-${YARD_IMG_ARCH}-${boot_mode}.img"
 image_url=${IMAGE_URL:-"https://${host}/${image_path}"}
 sha256sums_path="${release}/current/SHA256SUMS"
 sha256sums_url=${SHA256SUMS_URL:-"https://${host}/${sha256sums_path}"}
 
-imgfile="${workspace}/yardstick-${release}-server"
-raw_imgfile="${workspace}/yardstick-${release}-server.raw"
+imgfile="${workspace}/yardstick-dpdk-image.img"
+raw_imgfile_basename="yardstick-${release}-server.raw"
+raw_imgfile="${workspace}/${raw_imgfile_basename}"
 filename=$(basename $image_url)
+
+apt-get install -y parted
 
 # download and checksum base image, conditionally if local copy is outdated
 download() {
@@ -57,29 +65,35 @@ download() {
     cd $workspace
     rm -f SHA256SUMS # always download the checksum file to a detect stale image
     wget $sha256sums_url
-    test -e $filename || wget -nc $image_url
+    test -e $filename || wget -nc --progress=dot:giga $image_url
     grep $filename SHA256SUMS | sha256sum -c ||
     if [ $? -ne 0 ]; then
         rm $filename
-        wget -nc $image_url
+        wget -nc --progress=dot:giga $image_url
         grep $filename SHA256SUMS | sha256sum -c
     fi
+
+    for i in $(seq 0 9); do
+        [ -a /dev/loop$i ] || mknod -m 660 /dev/loop$i b 7 $i
+    done
+
     qemu-img convert $filename $raw_imgfile
     cd -
 }
 
 # mount image
 setup() {
+    # qemu-img resize $raw_imgfile +5GB
     mkdir -p $mountdir
-
-    for i in $(seq 0 9); do
-        [ -a /dev/loop$i ] || mknod -m 660 /dev/loop$i b 7 $i
-    done
 
     loopdevice=$(kpartx -l $raw_imgfile | head -1 | cut -f1 -d ' ')
 
-    kpartx -a $raw_imgfile
+    kpartx -av $raw_imgfile
 
+    # for trouble shooting
+    sleep 2
+    dmsetup ls
+    parted -l /dev/${loopdevice:0:5} || true
     mount /dev/mapper/$loopdevice $mountdir
     mount -t proc none $mountdir/proc
 
@@ -88,6 +102,9 @@ setup() {
     sudo resize2fs /dev/mapper/$loopdevice
 
     cp $cmd $mountdir/$(basename $cmd)
+    if [ "${YARD_IMG_ARCH}" = "arm64" ]; then
+        cp /usr/bin/qemu-aarch64-static $mountdir/usr/bin
+    fi
 }
 
 # modify image running a script using in a chrooted environment
@@ -120,9 +137,16 @@ cleanup() {
     # designed to be idempotent
     mount | grep $mountdir/proc && umount $mountdir/proc
     mount | grep $mountdir && umount $mountdir
-    if [ -f $raw_imgfile ]; then
+    mount | grep "/mnt/${release}" && umount "/mnt/${release}"
+
+    if [ -f "${raw_imgfile}" ]; then
+        #kpartx -dv $raw_imgfile sometimes failed, we should checked it agein.
+        #if [ -z "$(kpartx -l $raw_imgfile | grep 'loop deleted')" ]; then
+        #    kpartx -dv $raw_imgfile
+        #fi
         kpartx -dv $raw_imgfile || true
     fi
+
     rm -f $raw_imgfile
     rm -rf $mountdir
 }
@@ -137,6 +161,8 @@ error_trap()
     if [ -z "$exitcode" ]; then
         exitcode=$rc
     fi
+
+    dmesg -T | tail -50
 
     cleanup
 
@@ -153,6 +179,7 @@ main() {
     download
     setup
     modify
+
     trap - EXIT SIGTERM
     cleanup
 
